import { cn } from "@/lib/utils";
import {
  IconShieldLock,
  IconCloud,
  IconAlertTriangle,
  IconFireExtinguisher,
  IconDashboard,
  IconBug,
  IconClipboardCheck,
  IconUsers,
  IconNetwork,
  IconFingerprint,
  IconCode,
  IconSearch,
  IconLockAccess,
  IconDevices,
  IconCurrency,
  IconEye,
} from "@tabler/icons-react";

export default function FeaturesSectionDemo() {
  const features = [
    {
      title: "DevSecOps Integration",
      description: "Seamlessly integrate security practices into your development pipeline, ensuring robust protection from code to deployment.",
      icon: <IconShieldLock />,
    },
    {
      title: "Cloud Security Solutions",
      description: "Implement comprehensive security measures for AWS, GCP, and Azure environments, safeguarding your cloud infrastructure.",
      icon: <IconCloud />,
    },
    {
      title: "Threat Intelligence & Management",
      description: "Proactively identify and mitigate potential threats using advanced analytics and real-time monitoring systems.",
      icon: <IconAlertTriangle />,
    },
    {
      title: "Incident Response Planning",
      description: "Develop and implement robust incident response strategies to minimize damage and ensure rapid recovery from security breaches.",
      icon: <IconFireExtinguisher />,
    },
    {
      title: "Security Information and Event Management (SIEM)",
      description: "Deploy cutting-edge SIEM solutions for real-time analysis of security alerts generated by applications and network hardware.",
      icon: <IconDashboard />,
    },
    {
      title: "Penetration Testing & Vulnerability Assessment",
      description: "Conduct thorough penetration tests and vulnerability assessments to identify and address potential security weaknesses.",
      icon: <IconBug />,
    },
    {
      title: "Compliance & Risk Management",
      description: "Ensure adherence to industry standards and regulations (HIPAA, SOC2, GDPR) while effectively managing and mitigating cybersecurity risks.",
      icon: <IconClipboardCheck />,
    },
    {
      title: "Security Awareness Training",
      description: "Empower your team with comprehensive cybersecurity training programs, fostering a culture of security awareness throughout your organization.",
      icon: <IconUsers />,
    },
    {
      title: "Network Security Optimization",
      description: "Enhance your network's defenses with advanced firewalls, intrusion detection systems, and secure network architectures.",
      icon: <IconNetwork />,
    },
    {
      title: "Identity and Access Management (IAM)",
      description: "Implement robust IAM solutions to ensure secure, efficient, and compliant user access across your digital ecosystem.",
      icon: <IconFingerprint />,
    },
    {
      title: "Secure Code Review & Application Security",
      description: "Conduct in-depth code reviews and implement security best practices in application development to prevent vulnerabilities.",
      icon: <IconCode />,
    },
    {
      title: "Cyber Forensics & Incident Analysis",
      description: "Utilize advanced forensic techniques to investigate security incidents, determine root causes, and prevent future occurrences.",
      icon: <IconSearch />,
    },
    {
      title: "Zero Trust Architecture Implementation",
      description: "Design and deploy Zero Trust security models to enhance your organization's security posture in the modern digital landscape.",
      icon: <IconLockAccess />,
    },
    {
      title: "IoT Security Solutions",
      description: "Secure your Internet of Things (IoT) devices and networks with tailored security measures to protect against emerging threats.",
      icon: <IconDevices />,
    },
    {
      title: "Blockchain Security Consulting",
      description: "Provide expert guidance on securing blockchain implementations and smart contracts for financial and data integrity.",
      icon: <IconCurrency />,
    },
    {
      title: "Continuous Security Monitoring",
      description: "Implement 24/7 security monitoring solutions to detect and respond to threats in real-time, ensuring constant protection.",
      icon: <IconEye />,
    },
  ];

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4  relative z-10 py-10 max-w-7xl mx-auto">
      {features.map((feature, index) => (
        <Feature key={feature.title} {...feature} index={index} />
      ))}
    </div>
  );
}

const Feature = ({
  title,
  description,
  icon,
  index,
}: {
  title: string;
  description: string;
  icon: React.ReactNode;
  index: number;
}) => {
  return (
    <div
      className={cn(
        "flex flex-col lg:border-r  py-10 relative group/feature dark:border-neutral-800",
        (index === 0 || index === 4) && "lg:border-l dark:border-neutral-800",
        index < 4 && "lg:border-b dark:border-neutral-800"
      )}
    >
      {index < 4 && (
        <div className="opacity-0 group-hover/feature:opacity-100 transition duration-200 absolute inset-0 h-full w-full bg-gradient-to-t from-neutral-100 dark:from-neutral-800 to-transparent pointer-events-none" />
      )}
      {index >= 4 && (
        <div className="opacity-0 group-hover/feature:opacity-100 transition duration-200 absolute inset-0 h-full w-full bg-gradient-to-b from-neutral-100 dark:from-neutral-800 to-transparent pointer-events-none" />
      )}
      <div className="mb-4 relative z-10 px-10 text-neutral-600 dark:text-neutral-400">
        {icon}
      </div>
      <div className="text-lg font-bold mb-2 relative z-10 px-10">
        <div className="absolute left-0 inset-y-0 h-6 group-hover/feature:h-8 w-1 rounded-tr-full rounded-br-full bg-neutral-300 dark:bg-neutral-700 group-hover/feature:bg-blue-500 transition-all duration-200 origin-center" />
        <span className="group-hover/feature:translate-x-2 transition duration-200 inline-block text-neutral-800 dark:text-neutral-100">
          {title}
        </span>
      </div>
      <p className="text-sm text-neutral-600 dark:text-neutral-300 max-w-xs relative z-10 px-10">
        {description}
      </p>
    </div>
  );
};
